[env:esp32dev]
platform    = espressif32
board       = esp32dev
framework   = arduino

monitor_speed  = 115200
upload_speed   = 921600

lib_deps =
    beegee-tokyo/DHTesp @ ^1.8.0
    me-no-dev/ESP Async WebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
    bblanchon/ArduinoJson @ ^7.1.0

board_build.filesystem  = littlefs
board_build.partitions  = default.csv

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_ARDUHAL_LOG_COLORS=1
