[env:esp32dev]
platform    = espressif32
board       = esp32dev
framework   = arduino

monitor_speed  = 115200
upload_speed   = 921600

lib_deps =
    https://github.com/beegee-tokyo/DHTesp.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    bblanchon/ArduinoJson @ ^7.1.0

board_build.filesystem  = littlefs
board_build.partitions  = default.csv

extra_scripts = pre:scripts/build_html.py

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_ARDUHAL_LOG_COLORS=1
